/** @type {import('tailwindcss').Config} */
const fontLatin = ["Plus Jakarta Sans", "system-ui", "sans-serif"];
const fontThai = ["Noto Sans Thai", "system-ui", "sans-serif"];
const fontStack = [...fontLatin, ...fontThai.slice(1)];

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#004ac6",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        secondary: "#575e72",
        "on-secondary": "#ffffff",
        "secondary-container": "#dbe2fa",
        "on-secondary-container": "#5d6478",
        "secondary-fixed": "#dbe2fa",
        "secondary-fixed-dim": "#bfc6dd",
        "on-secondary-fixed": "#141b2c",
        "on-secondary-fixed-variant": "#3f4759",
        tertiary: "#6a1edb",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#8343f4",
        "on-tertiary-container": "#f7edff",
        "tertiary-fixed": "#eaddff",
        "tertiary-fixed-dim": "#d2bbff",
        "on-tertiary-fixed": "#25005a",
        "on-tertiary-fixed-variant": "#5a00c6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        danger: "var(--color-danger)",
        background: "#f8f9ff",
        "on-background": "#121c2a",
        surface: "#f8f9ff",
        "on-surface": "#121c2a",
        "on-surface-variant": "#434655",
        "surface-variant": "#d9e3f6",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "surface-tint": "#0053db",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#b4c5ff",
        outline: "#737686",
        "outline-variant": "#c3c6d7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        "container-margin": "16px",
        "container-margin-md": "24px",
        "container-margin-lg": "32px",
        gutter: "16px",
        "gutter-md": "24px",
      },
      padding: {
        safe: "env(safe-area-inset-bottom, 0px)",
      },
      zIndex: {
        nav: "var(--z-nav)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
      },
      fontFamily: {
        sans: fontStack,
        latin: fontLatin,
        thai: fontThai,
        "body-lg": fontStack,
        "display-lg": fontStack,
        "label-md": fontStack,
        "label-sm": fontStack,
        "label-lg": fontStack,
        "headline-md": fontStack,
        "headline-lg": fontStack,
        "headline-lg-mobile": fontStack,
        "body-md": fontStack,
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg-desktop": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "label-md": ["14px", { lineHeight: "1.35", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.35", fontWeight: "500" }],
        "headline-md": [
          "22px",
          { lineHeight: "1.35", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md-desktop": [
          "24px",
          { lineHeight: "1.4", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-lg": [
          "16px",
          { lineHeight: "1.35", letterSpacing: "0.005em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.25", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-md-desktop": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
